### PR TITLE
[THUNDERCORE] Add ThunderCore support

### PR DESCRIPTION
**Pull request by ashwinp-r**
### Description

ThunderCore is an EVM compatible, high-throughput blockchain

* Homepage: https://www.thundercore.com
* RPC: https://mainnet-rpc.thundercore.com
* BIP44 1001/ ChainId 108 (https://github.com/satoshilabs/slips/pull/371)

### Changes

* This PR adds ThunderCore support
* Standard chain support changes

### CODE REVIEW

**Comment by nickmccurdy** [comment]
@Azarielle Ready for QA

**Comment by ashwinp-r** [comment]
@everyone thanks for the quick reviews! Do you guys know when this PR will likely be merged/available?

**Comment by nickmccurdy** [comment]
We should be releasing this next week.

**Comment by Azarielle** [comment]
Merged in #2410

**Comment by nickmccurdy** [comment]
Thanks for the contribution, this has been published in MyCrypto 1.6.1.

**Pull request closed without merging**
