### PR TITLE
Add support for the Archos Safe-T mini hardware wallet

### PR DESCRIPTION
**Pull request by jcrona**
### Description

These commits add support for the Archos Safe-T mini hardware wallet in MyCrypto. An option to Connect & Sign using the Safe-T mini has been added next to the one for the TREZOR.

### Changes

* Relevant files for the Archos Safe-T mini have been created based on what has been done for the TREZOR (but no electron support for now).

### Steps to Test

The Archos Safe-T mini has been tested successfully on testnet and livenet.
To test the Safe-T mini support, you just need to select Connect & Sign via Archos Safe-T mini, and follow the instructions.
If someone from the MyCrypto team wants to test it, we would be happy to offer him/her an Archos Safe-T mini (it is not for sale yet).

### Screenshots

screenshot_20180614_113309

### CODE REVIEW

**Comment by dternyak** [comment]
Hey @jcrona!

Thanks a lot for this PR. More hardware wallets are always welcome!

Could I ask you to split up this PR into two, one for french translations and one for the logic? I'm happy to merge the french translation first, since we won't need as much review there as we do on the logic.

Looking forward to working with you on getting this reviewed and integrated into MyCrypto!

**Comment by jcrona** [comment]
Done. French translations PR is #1970.
Once #1970 merged, this one will conflict on fr.json, but this is very easy to resolve.

@dternyak, let me know if there is anything else I need to do !

**Comment by wbobeirne** [comment]
The code here all looks great, you really did an excellent job matching the other wallet's styles. I can't drop an "approve" on here without being able to test it though. I just had two questions:

1. Is there a way you can maintain and publish a safe-t-connect npm module? We'd like to vendor as few libraries as possible.
2. Have you all developed a way to interface with the device natively via node? We'll need to do a separate integration to work on the native application if so.

Thanks for doing the legwork on this.

**Comment by dternyak** [comment]
@jcrona You've got a few conflicts here, mind fixing? :)

**Comment by jcrona** [comment]
@dternyak done !

@wbobeirne we should be able to integrate the Safe-T mini into the native app more or less the same way it has been done for the Trezor, but let's do it as a second step.

**Comment by dternyak** [comment]
@jcrona I noticed that the fade-in animation isn't hitting the 5th option in our secure row due to the introduction of Safe-T. Do you mind updating this PR so that all wallet unlock options are animated?

**Comment by tayvano** [comment]
### Good to go
-  Archos works on https://mycryptobuilds.com/c8777ef258037f11ed89c0973663a1bf14321d35/
-  Is grayed out (like TREZOR) for sign message page
- Jordan successfully received and sent funds on the `c8777ef258037f11ed89c0973663a1bf14321d35` commit

### TODO Desktop App
- Has “not yet implemented” on desktop. Lets update this interaction to match the “Web3" interaction where the item is grayed out and has the tooltip.
   - Copy for Archos tooltip: “Coming soon. Please use the MyCrypto.com website in the meantime.”

### TODO Web & Desktop Version 

- Animation needs to be updated: I think it's these lines? https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/components/WalletDecrypt/components/WalletButton.scss#L33-L37?

### TODO As Separate PRs

- The new layout has it’s own github issue (https://github.com/MyCryptoHQ/MyCrypto/issues/1965) that we can handle as a separate PR once this is merged or include the layout change in this PR as well.

- Create new support articles. Add links to website to these support articles.

**Comment by jcrona** [comment]
@dternyak The animation issue has been fixed !

**Pull request merged**
