### PR TITLE
Update LRC token information in eth.json 

### PR DESCRIPTION
**Pull request by dong77**
## Description
Upgrade LRC token info.

## Changes
Change the LRC (Loopring) token address to reflect the updated contract. For more information, please see: https://medium.com/loopring-protocol/lrc-token-upgraded-a26ee6f87b84

## Steps to Test

No need to run test

## Quality Assurance

- [x] The branch name is in lowercase-kebab-case with no prefix (unless it was created from Clubhouse)
- [x] The base branch is develop or gau (no nested branches)
- [ ] This is related to a maximum of one Clubhouse story or GitHub issue
- [x] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] If code is copied from existing directories, there is an explanation of why this is necesary in the description/changes, and all copying is done in separate commits to make them easy to filter out

### CODE REVIEW

**Comment by blurpesec** [comment]
We import these token definitions from https://github.com/ethereum-lists/tokens/ so when we pull from there next, it will overwrite your changes here. Can you go and update the address for the Loopring token there please? :)

**Comment by dong77** [comment]
I have already submitted a PR on that repo - https://github.com/MyEtherWallet/ethereum-lists/pull/1275

Shall I close this one then? Or if it doesn't hurt, I prefer still merging this PR so the token information is in sync.

**Comment by dong77** [comment]
I created a PR for that repository (https://github.com/ethereum-lists/tokens/pull/261), but I feel it will be great if we can also update the information here so they are in sync. What do you think, @blurpesec?

**Comment by wtzb** [comment]
@dong77 it's merged in ethereum-lists now, changes will be reflected in the next update :)

**Pull request closed without merging**
