### PR TITLE
Electron sandbox

### PR DESCRIPTION
**Pull request by 409H**
[CH6072]

## Closes https://github.com/MyCryptoHQ/MyCrypto/issues/3261

🎉 🎉 🎉

## Description

* Put the main `BrowserWindow` into `sandbox` mode
* Removed unneeded Shapeshift code since we disabled it in https://github.com/MyCryptoHQ/MyCrypto/pull/3153 (needed to remove due to failing build whilst in `sandbox` mode)

#### TODO

- [x] Fix tests
- [x] QA

## Changes

* Enabled sandbox mode
* Removed unnecessary code

## Quality Assurance

- [ ] The branch name is in lowercase-kebab-case with no prefix (unless it was created from Clubhouse)
- [ ] The base branch is develop or gau (no nested branches)
- [ ] This is related to a maximum of one Clubhouse story or GitHub issue
- [ ] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] If code is copied from existing directories, there is an explanation of why this is necesary in the description/changes, and all copying is done in separate commits to make them easy to filter out
- [ ] If your code adds new text to the UI, the added text is [translatable](https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributing---Translatable-strings)

### CODE REVIEW

**Comment by vilsbole** [comment]
The tests were failing because legacy still uses snapshots, which needed to be updated eg. `jest --updateSnapshots` after adding a network. It's odd that it arises only on this PR. 

Screenshot 2020-05-13 at 15 59 37

**Comment by 409H** [comment]
@vilsbole after testing functionality, everything seems to work (note: I don't have a trezor yet to test though I believe it won't be broken)

**Comment by vilsbole** [comment]
@wtzb @Mrtenz can we plan a fast release for this PR?

**Comment by wtzb** [comment]
@vilsbole release tagging day was yesterday, but if everything is tested well, I can do a new release asap.

**Pull request merged**
