### PR TITLE
Reset Contracts-Interact tab on network change

### LINKED ISSUE #1904: Contract address is retained even after leaving the page
contract address

### LINKED ISSUE #2043: Contract ABI persists when changing nodes
However, "Select Existing Contract" and "Contract Address" get cleared

abistays

### PR DESCRIPTION
**Pull request by mwbailey**
Closes #2043 
Closes #1904 

### Description

Clears all fields in the Interact tab (contract name, address, and ABI/JSON interface) and closes the contract explorer, if open, when a user switches to a new network.

### Changes

InteractForm gets the current network as a prop from the Redux store. When the network changes, the fields are cleared and a new instance of the Dropdown component is created (otherwise, Dropdown's `selectedOption` will retain its previous value).

### Steps to Test

1. Go to the Contracts-Interact tab
2. Select a contract and click 'Access'
3. Select a different network in the top-right dropdown menu
4. Verify that all fields are cleared and the list of available contracts has been updated to reflect the new network

### CODE REVIEW

**Comment by ConnorBryan** [comment]
@mwbailey 
Can we update this to use the new feature pattern of config? You can see other files that use redux for examples.

**Comment by mwbailey** [comment]
Sure thing! I'll have some time this weekend.

**Comment by mwbailey** [comment]
@ConnorBryan 
I updated the PR to use configSelectors when getting the redux state.

I also added componentWillUnmount() to reset the contract address when the user selects a different tab. Otherwise, the 'Contract Address' field retains the previous value when the user leaves the tab and returns. Just realized after I pushed the updates that there's an open issue for this (#1904), so I edited the PR to close that issue as well.

**Comment by tayvano** [comment]
@Mrtenz Can you review and see if this is worth adddressing, etc. still

**Comment by vilsbole** [comment]
This PR was automatically closed because the base branch `develop` has been deleted. 
If you wish you are welcome to submit you PR again against `master`.

**Pull request closed without merging**
