### PR TITLE
Sweeper Component

### PR DESCRIPTION
**Pull request by oojr**
work in progress, For the next parts, I am thinking of creating a new redux saga` function* estimateBatchGasCost`, I also need to create a new redux key to create a list of transactions

### CODE REVIEW

**Comment by dternyak** [comment]
Hey @oojr,

I hope things are going well on your side.

We didn't make this as clear as we should have initially, but ideally this work would get done in the next 1-2 weeks.

Just wanted to make sure you're still up for that sort of deadline :)

**Comment by oojr** [comment]
@dternyak I'm up for it, I want to try to have most of the functionality done sooner than a week and have it reviewed

**Comment by oojr** [comment]
@dternyak @HenryNguyen5 

Before scanning for tokens

screen shot 2018-01-29 at 7 46 18 am

The screen after scanning for tokens

screen shot 2018-01-29 at 7 48 14 am

**Comment by oojr** [comment]
@dternyak @HenryNguyen5 the balances component inside the sweeper page is not going to work like that, I feel I need to keep a different list of tokens with different state, similar to this.state.trackedTokens in `Balances.tsx`, I am thinking of adding another component like Balances but it is a a table/checkbox list so the user can know which token has been broadcasted and if that token is mined into a block

**Comment by dternyak** [comment]
@oojr Sure, feel free to create new components as necessary. 

We're getting close to the 1 week mark since we last discussed - are you still planning on having a reviewable PR in the next few days?

**Comment by oojr** [comment]
@dternyak I have a good idea on what I want to do, i'll have something reviewable today or tomorrow if I don't run into any roadblocks

**Comment by oojr** [comment]
@dternyak update on this, I am thinking about how to architect a saga at the moment, looping through with a for..of and adding doing a yield put for each token that needs to be sent with setUnitMeta action, trigger the estimateGas saga, and save the batch with estimates in a new store is my plan

**Comment by oojr** [comment]
@HenryNguyen5 @dternyak  I think I might have to pass this over to someone with more expertise, I need to gather a better understanding of how sending a transaction works, 

the flow I was targeting for was estimating transactions one by one and keeping a list of token balances with information if the transaction was broadcasted or not

**Comment by wbobeirne** [comment]
That's fair @oojr, this was by no means a small task. Thanks for taking a swing at it. I'm going to close this PR out, but the code will be around for whoever picks it up next, and they can decide if they want to build off of what you got started with.

**Pull request closed without merging**
