### PR TITLE
Add energy web networks

### PR DESCRIPTION
**Pull request by manihagh**
## Description

Add Energy Web networks

## Changes

Add Energy Web networks (EnergyWeb Volta test and EnergyWeb production chain networks)

### CODE REVIEW

**Comment by vilsbole** [comment]
@manihagh we are currently pruning the networks that we support. Can you contact me on our [discord](https://discord.gg/fPD8dT) to explain your why you want to add an enterprise network?

**Comment by manihagh** [comment]
> @manihagh we are currently pruning the networks that we support. Can you contact me on our [discord](https://discord.gg/fPD8dT) to explain your why you want to add an enterprise network?

Thanks, sure. EnergyWeb is public blockchain network. Can you please send me the invite again? Thank you.

**Comment by vilsbole** [comment]
Here is the invite again: https://discord.gg/nNu83V

Reading the instructions on https://www.energyweb.org/work-with-us/become-a-member/ I see:
> Validator Node Qualification
Member may undergo a process of qualification by which it will be labeled eligible to run a Validator Node in the Energy Web Chain.

Which seems to make it a permissioned chain hence a private chain.

**Comment by ngyam** [comment]
Hi @vilsbole, only the validator set is permissioned but the chain is public, hence it is not a private chain. The native tokens are publicly traded and available, we are supported by Trezor and Ledger as well. Anybody can freely build and access DApps or send transactions without permission. Anybody can become a validator who fits the criteria determined by our governance.

**Comment by manihagh** [comment]
> Here is the invite again: https://discord.gg/nNu83V
> 
> Reading the instructions on https://www.energyweb.org/work-with-us/become-a-member/ I see:
> 
> > Validator Node Qualification
> > Member may undergo a process of qualification by which it will be labeled eligible to run a Validator Node in the Energy Web Chain.
> 
> Which seems to make it a permissioned chain hence a private chain.

EWC is a PoA(Proof of Authority) public blockchain network. The instruction you referred is the process to become a Validator on the chain. There are several other PoA type networks in MyCrypto supported networks as well. Any interaction with the chain is publicly available without restrictions.

**Pull request merged**
