### PR TITLE
Used AddressField component for Contracts

### PR DESCRIPTION
**Pull request by FrederikBolding**
- Used AddressField component for Contracts
- Fixed some validation issues

### CODE REVIEW

**Comment by FrederikBolding** [comment]
[ch4308]

**Comment by FrederikBolding** [comment]
Fixed merge conflicts 👍

**Comment by MrLuit** [comment]
I tried to save a contract (0x89205a3a3b2a69de6dbf7f01ed13b2108b2c43e7), but the following error appeared:

image

**Comment by FrederikBolding** [comment]
Fixed part of the problem - waiting on clarification by Emmanuel on a few things.

**Comment by vilsbole** [comment]
Merging even though Windows build fails since we have decided to suspend support for electron at the time being.

**Pull request merged**
