### PR TITLE
Add account styling fixes

### PR DESCRIPTION
**Pull request by SharonManrique**
https://mycryptobuilds.com/pr/2535/#/add-account

CW-22, 23, 24, 25, 26, 27, 28

- Fixes styling of all wallets in add-existing-account-views. Padding, margins, alignment etc. 

TODO: 

- [ ] Mobile views
- [ ] Translatable strings

### CODE REVIEW

**Comment by nickmccurdy** [comment]
https://app.clubhouse.io/mycrypto/story/685/add-account-styling-fixes

**Comment by SharonManrique** [comment]
@nickmccurdy 

Ledger/Trezor etc. 
> When unlocking button should disappear and loading indicator should look like designs.

A button should remain here incase "unlocking" needs to be triggered/if theres an error. 

>Unlock button should say Confirm Transaction.

This isn't signing any transaction, this is just unlocking wallet.

**Comment by nickmccurdy** [comment]
> A button should remain here incase "unlocking" needs to be re-triggered/if theres an error.
Good point, but I still think it makes sense to remove the button when the in progress text isn't actionable, and it could switch back to a button if it's cancelled.

**Comment by SharonManrique** [comment]
@nickmccurdy Button has been removed and renders spinner only unpon unlocking wallet.

**Comment by SharonManrique** [comment]
@nickmccurdy 
> * [ ]  Is it intentional that "Sign the transactions with" in headings is replaced with "Connect and Unlock"?
> * [ ]  Safe-T Mini help text: Don’t have a Safe-T Mini? Get one now. [link]
> * [ ]  Private Key help text: Because we never save, store, or transmit your secret, you need to sign each transaction in order to send it. MyCrypto puts YOU in control of your assets.
> * [ ]  Mnemonic Phrase help text: Because we never save, store, or transmit your secret, you need to sign each transaction in order to send it. You are always in control of your assets with MyCrypto!
> * [ ]  Keystore File help text: Because we never save, store, or transmit your secret, you need to sign each transaction in order to send it. MyCrypto puts YOU in control of your assets.

- Its the send tranaction flow. Its the unlock wallet flow. The linked designs were models. 
- The SafeT mini link is consistent with the other wallets.

**Comment by nickmccurdy** [comment]
Sorry I was confused about the flow designs, I removed the irrelevant items from my review

**Comment by nickmccurdy** [comment]
Please wait to merge, I am working on styling issues 
image

**Comment by SharonManrique** [comment]
@nickmccurdy Emmanuel is taking care of this with his styling fixes

**Comment by Sonicrida** [comment]
When I try to connect to Metamask without being logged in to the plugin, I get this error in the console `No accounts found in MetaMask / Web3.` but it is never displayed to the user. 

image

Hitting back takes me out of the app if it is the first route I entered. This should probably be taking us back to the add-account page?

**Pull request merged**
