### PR TITLE
Add support for iOlite Network

### LINKED ISSUE #2205: Add support for iOlite
### Add support for iOlite
```
bitcointalk ANN    : https://bitcointalk.org/index.php?topic=2997516.0
homepage           : https://iolite.io
block explorer     : https://scan.iolite.io
node               : https://net.iolite.io
slip0044 index     : 1171337
chainId            : 18289463
```

### PR DESCRIPTION
**Pull request by vldmkr**
Closes #2205

### Description

Iolite is a network based on the Ethereum code base. Technically, Iolite extends the typical transaction by adding meta information from the smart contract creation framework.

```
bitcointalk ANN    : https://bitcointalk.org/index.php?topic=2997516.0
homepage           : https://iolite.io
block explorer     : https://scan.iolite.io
node               : https://net.iolite.io
slip0044 index     : 1171337
chainId            : 18289463
```
iolite-parity repository: https://github.com/iolitelabs/iolite-parity
live version if any tests are required: https://mycrypto.iolite.io/?network=ILT

### Changes
This PR adds iOlite Network support

### CODE REVIEW

**Comment by ConnorBryan** [comment]
@vldmkr Sorry for the late reply; could you fix up this conflict?

**Comment by vldmkr** [comment]
@ConnorBryan Anyway, thanks for the response! Please review the fix I made.

**Comment by ConnorBryan** [comment]
@vldmkr I had to revert; our QA found issues with SendTransaction after this PR.

**Comment by vldmkr** [comment]
@ConnorBryan Can you give more details? Problems with **SendTransaction** with all networks or only with the iOlite network? Quite a lot of code has changed since the PR, maybe there were problems when merging?

**Pull request merged**
