### PR TITLE
Update reducer.ts - rename EGT to EGEM

### PR DESCRIPTION
**Pull request by riddlez666**
rename EGT to EGEM

### CODE REVIEW

**Comment by dternyak** [comment]
Do you mind pointing me towards an official source that discusses this rename so I can verify these proposed changes?

**Comment by dternyak** [comment]
@riddlez666 Just pinging you on that reference.

**Comment by dternyak** [comment]
Hey @riddlez666, I'm going to close this PR for now. Feel free to comment back with a reference and I'll be happy to reopen!

**Comment by riddlez666** [comment]
https://egem.io OUR TICKER IS EGEM, even myetherwallet has it and my original PR had the correct ticker.

**Comment by riddlez666** [comment]
https://github.com/MyCryptoHQ/MyCrypto/pull/1862

**Comment by riddlez666** [comment]
@dternyak

**Comment by riddlez666** [comment]
https://github.com/MyCryptoHQ/MyCrypto/pull/1689/files

**Comment by riddlez666** [comment]
my question to... thank you very much!

**Pull request merged**
