### PR TITLE
[FEATURE] Upgrade EAC libs to v1.0.0-beta.3.

### PR DESCRIPTION
**Pull request by Kuzirashi**
### Description

Ethereum Alarm Clock released new version 1.0.0-beta.3 hence the need to upgrade addresses and validation (smart-contract side).

### Changes

- Update EAC Kovan addresses
- Update validation code to match 1.0.0-beta.3 version

### Steps to Test

Schedule transaction.

### CODE REVIEW

**Comment by dternyak** [comment]
@Kuzirashi I tested this on mycryptobuilds, and I generated a tx that shows up on etherscan, but not on chronos.

https://app.chronologic.network/transactions/0x4b47cbed47de1033794838dbbfbe1af4327a38dc

Do you mind looking into this?

**Comment by Kuzirashi** [comment]
Hello @dternyak, it's because we're waiting with our app.chronologic.network deploy for MyCrypto deploy. You can test it on: http://chronologic-dev.s3-website-us-east-1.amazonaws.com

**Comment by dternyak** [comment]
@Kuzirashi Cool! Thanks for letting me know. Do you know when the new deploy is scheduled for? It would be great to make sure users can see their scheduled transaction in chronologic once this is merged.

**Comment by Kuzirashi** [comment]
@dternyak We will deploy ASAP when you deploy new version of MyCrypto. We're waiting just for this PR. : P

**Comment by dternyak** [comment]
@Kuzirashi Got it! :)

**Pull request merged**
