### PR TITLE
Remove tipjar from contacts

### PR DESCRIPTION
**Pull request by FrederikBolding**

### CODE REVIEW

**Comment by FrederikBolding** [comment]
[ch8243]

**Review by GuillaumeRx — CHANGES_REQUESTED** [review]
Please add a new migration in persist.config to remove the mycrypto tip jar if it exists in LS

**Comment by FrederikBolding** [comment]
@GuillaumeRx I asked Jordan about this and we decided just to do it for new users. Do you think its important?

**Comment by GuillaumeRx** [comment]
@FrederikBolding nope I tough it might be better if it was removed for everyone :) But if you prefer as it is I'm also fine with it

**Comment by FrederikBolding** [comment]
@GuillaumeRx Not a big deal imo.

**Review by GuillaumeRx — APPROVED** [review]
We can always add the migration later, merging

**Pull request merged**
