### PR TITLE
Replace existing AddAccountFlow scss with new components

### PR DESCRIPTION
**Pull request by FrederikBolding**
Removed `AddAccountFlow.scss`, replaced with components. 

Also fixes a bug where the scss wouldn't be loaded for VerifyMessage and SignMessage and thus the styling would be off.

### CODE REVIEW

**Review by GuillaumeRx — CHANGES_REQUESTED** [review]
code lgtm;

You're just missing a whitespace on the ledger panel :)

Screenshot 2020-11-30 at 17 03 47

**Comment by GuillaumeRx** [comment]
Oh I'm not having this issue

**Comment by FrederikBolding** [comment]
@GuillaumeRx It only happened at certain resolutions, should be fixed now

**Review by vilsbole — APPROVED** [review]
lgtm;

**Comment by GuillaumeRx** [comment]
@FrederikBolding I think it's missing whitepaces one the `comprehensive troubleshooting guide` sentence ?

**Review by GuillaumeRx — APPROVED** [review]
No missing white-spaces, apparently it's a weird font thing. Good to go :)

**Pull request merged**
