### PR TITLE
Feature/download desktop app

### PR DESCRIPTION
**Pull request by PeterZlodej**
This PR includes download desktop app view and analytics.

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Thanks, the code looks solid and the failure is the same as in the GAU branch. How do I access the download page to see it? I don't see create wallet in the navbar.

**Comment by PeterZlodej** [comment]
> Thanks, the code looks solid and the failure is the same as in the GAU branch. How do I access the download page to see it? I don't see create wallet in the navbar.

This PR does not include the navigations from the navbar or from the homepage yet. Currently, it can be accessed directly at path "/download-desktop-app"

**Comment by nickmccurdy** [comment]
Thanks, it looks good!

**Comment by SharonManrique** [comment]
Works on Linux, and Windows. Needs check on mac.

**Comment by nickmccurdy** [comment]
Works on macOS.

**Pull request merged**
