### PR TITLE
Removed legacy libs and things dependant on them

### PR DESCRIPTION
**Pull request by FrederikBolding**
- Libs
- UI elements depending on libs
- Fixed imports on existing tests

### CODE REVIEW

**Comment by FrederikBolding** [comment]
@vilsbole No, I haven't looked at them much. There might be some stuff, but we'll have to write new tests for that then? 😄

**Comment by vilsbole** [comment]
@FrederikBolding I looked at `decrypt.spec.ts` and it would be good to keep the tests and point them the appropriate methods that have been copied to v2.
The same for all the other spec files [if methods exists in v2 ? change import to v2 : delete spec]

**Comment by FrederikBolding** [comment]
@vilsbole Sure! I'll go through them and see which should be kept 👍

**Comment by FrederikBolding** [comment]
@vilsbole Saved most of the tests!! 👍

**Pull request merged**
