### PR TITLE
Add EVRICE network

### PR DESCRIPTION
**Pull request by EVRICE**
## Closes #ISSUE_NUMBER_GOES_HERE

🎉 🎉 🎉

## Description

......

## Changes

* High level
* changes that
* you made

## Steps to Test

1. Steps
2. to
3. test

## Quality Assurance

- [ ] The branch name is in lowercase-kebab-case with no prefix (unless it was created from Clubhouse)
- [ ] The base branch is develop or gau (no nested branches)
- [ ] This is related to a maximum of one Clubhouse story or GitHub issue
- [ ] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] If code is copied from existing directories, there is an explanation of why this is necesary in the description/changes, and all copying is done in separate commits to make them easy to filter out
- [ ] If your code adds new text to the UI, the added text is [translatable](https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributing---Translatable-strings)

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Heya! Thanks for your contribution! Can you please combine the changes of #3917 #3918 & #3919 in a single PR? In that way we can process it all at once 😄 

I'll close the others and we can take any further discussion in this thread.

Let me know if you have any questions.

**Comment by FrederikBolding** [comment]
@EVRICE I have combined your PRs here for you. I noticed that you are using ETH DPaths for your network, is that intentional?

**Comment by EVRICE** [comment]
Thank you very much for the help! About ETH DPATH - I left it as in other networks. We have not made any changes on this part.

**Comment by FrederikBolding** [comment]
> Thank you very much for the help! About ETH DPATH - I left it as in other networks. We have not made any changes on this part.

I just want to be sure that you are intending to use the ETH DPath for your network. You are supposed to use the slip44 value https://github.com/satoshilabs/slips/blob/master/slip-0044.md, but you are currently using `60` which is the Ethereum slip44 value. Please verify that this is intentional 😄

**Comment by EVRICE** [comment]
Thank you for writing to us. This is not done intentionally. No one can contact our programmer yet. But if you can tell us about this moment, we will be very happy! For example, we want to make slip44 - 1020 (0x800003fc). Can this affect existing wallets and balances? And how can this be done?

**Comment by FrederikBolding** [comment]
> Thank you for writing to us. This is not done intentionally. No one can contact our programmer yet. But if you can tell us about this moment, we will be very happy! For example, we want to make slip44 - 1020 (0x800003fc). Can this affect existing wallets and balances? And how can this be done?

If you want to use a slip44 of 1020 you would use the DPath `m/44'/1020'/0'/0`. This would only effect mnemonic phrases where you might have already selected an address using the old DPath. Users can add via multiple DPaths on MyCrypto so it isn't an issue, but you should use your correct DPath as the default if possible 👍

**Review by EVRICE — COMMENTED** [review]
Add DPaths.EVRICE_DEFAULT

**Review by blurpesec — APPROVED** [review]

**Pull request merged**
