### PR TITLE
Fix Electron not running

### PR DESCRIPTION
**Pull request by LinFeiLong**
Fix Electron crash after this commit ([#2895)](https://github.com/MyCryptoHQ/MyCrypto/pull/2895)

### CODE REVIEW

**Comment by FrederikBolding** [comment]
I think we should try to use the v2 methods. When is the crash happening?

**Comment by FrederikBolding** [comment]
Also, I don't see the difference between the `v2` methods and the old ones.

**Comment by LinFeiLong** [comment]
It's not really a crash, it's a warning/alert window.
And the Electron App won't launch.
I tried to fix it. But I don't really understand why it is not working.
Looks like the electron app cant find some functions.

**Comment by LinFeiLong** [comment]
Closing since it is fixed on [2898](https://github.com/MyCryptoHQ/MyCrypto/pull/2898)

**Pull request closed without merging**
