### PR TITLE
Add existing account views: Select Address

### PR DESCRIPTION
**Pull request by nickmccurdy**
This includes the UI (only) for [CW-29](https://mycrypto.atlassian.net/browse/CW-29).

image

## [Flow Spec](https://mycrypto.atlassian.net/wiki/spaces/CORE/pages/132644937/Add+Existing+Account+Flow (section 4a))

Most UI steps are implemented except where they depend on unfinished logic development work.

## Manual Testing
1. Visit https://mycryptobuilds.com/add-existing-account-views-select-address/#/add-account (or http://localhost:3000/add-account with `yarn start`)
2. Click `Mnemonic Phrase`, `Ledger`, `Trezor` or `Safe-T mini`
3. Unlock your wallet and click `Choose address`

## Tasks

- [x] Use "No Label" titles
- [x] Header layout
- [x] Table data formatting for updated design
- [x] Background height
- [x] Horizontal table margins
- [x] New table button styles
- [x] Derivation path label
- [x] Let ETH column break
- [x] Remove token column (at least until we decide that we need it)
- [x] Update https://github.com/MyCryptoHQ/ui/pull/55
- [x] Fix font sizes
- [x] Connect to hardware wallets (Ledger, Trezor, and Safe-T Mini)
- [x] Fix next page button in mycryptobuilds/production
- [x] Fix panel layout for hardware wallets (Ledger, Trezor, and Safe-T Mini)
- [x] Custom dpath form styles

## Later
- [ ] Decide if we want to implement token dropdown/column
- [ ] 'Cancel' button is missing an outline

### CODE REVIEW

**Comment by tayvano** [comment]
Can we add a label above the dropdown with a question mark thing that links to a KB article? Makes it easier to understand for people and easier to refer to when helping people

https://mycryptohq.slack.com/archives/G8G1S4TG9/p1555615879242800


all the fonts in the table -> `1rem`
all the padding -> `1rem 0.5rem`
min-width -> `1rem`
identicon -> `2.75rem`

make the table full width of the panel

```
width: calc(100% + 3rem);
margin: 0 -1.5rem;
```

address div should have a `align-items: center;`

addresses should be `monospace` font

remove the nbsp; for the ETH value. let it break onto 2 lines or maybe even force it to break on two lines so its consistent.

https://mycryptohq.slack.com/archives/G8G1S4TG9/p1555614599240000


Screenshots in slack

**Comment by nickmccurdy** [comment]
I've updated UI and the select address styles, trying to fix as many suggestions as possible while staying somewhat consistent with the design and UI. Please let me know if you have further suggestions.

**Comment by nickmccurdy** [comment]
Finished, unless we decide to make style or logic changes before integrating

**Comment by CryptoQueen628** [comment]
https://app.clubhouse.io/{org}/story/{11}

**Comment by CryptoQueen628** [comment]
[ch11]

**Comment by CryptoQueen628** [comment]
https://app.clubhouse.io/mycrypto/story/11/as-an-existing-user-i-want-to-select-an-address-from-hd-derivation-paths-to-access-my-eth

**Comment by CryptoQueen628** [comment]
https://app.clubhouse.io/mycrypto/story/11/as-an-existing-user-i-want-to-select-an-address-from-hd-derivation-paths-to-access-my-eth

**Comment by CryptoQueen628** [comment]
https://app.clubhouse.io/mycrypto/story/11/as-an-existing-user-i-want-to-select-an-address-from-hd-derivation-paths-to-access-my-eth

**Comment by CryptoQueen628** [comment]
https://app.clubhouse.io/mycrypto/story/11/as-an-existing-user-i-want-to-select-an-address-from-hd-derivation-paths-to-access-my-eth

**Comment by nickmccurdy** [comment]
https://app.clubhouse.io/mycrypto/story/45/i-want-to-select-the-correct-derivation-path-to-unlock-my-account

**Pull request merged**
