### PR TITLE
Identifying Trust Wallet Web3 Provider

### PR DESCRIPTION
**Pull request by hewigovens**
### Description

[Trust Wallet](https://trustwalletapp.com/) is a secure, open source, decentralized and anonymous mobile wallet application that supports Ethereum and Ethereum based tokens.

We follow this [Guide](https://support.mycrypto.com/contributor-info/adding-support-for-web3-wallet.html) to identify Trust Wallet Web3 Provider.

### Changes

* Add constructor name `TrustWeb3Provider` and  localization id to `X_TRUST`
 to `Web3ProviderInfo`
* Add Trust Wallet svg logo

### CODE REVIEW

**Comment by ConnorBryan** [comment]
@hewigovens We're having trouble replicating your screenshot with this; what were the steps you took to get it?

**Comment by ConnorBryan** [comment]
Per Victor from Trust Wallet:

"Some changes are being updated with regard to web3, we will let you know".

**Comment by hewigovens** [comment]
@ConnorBryan Could you please try Trust Wallet iOS (version 1.112.0 App Store) again ? The screenshot in this issue is updated as well

**Comment by vikmeup** [comment]
@ConnorBryan it's good to go!

**Comment by tayvano** [comment]
Jordan + Taylor tested this on android and ios and works good.

**Pull request merged**
