### PR TITLE
Add 'Latest' button

### PR DESCRIPTION
**Pull request by james-prado**
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1819

### Description

Bring back 'latest' button

### Changes

- Remove gradient background on nav
- Add 'Latest' button

### Screenshots

screen shot 2018-06-08 at 5 39 28 am

### CODE REVIEW

**Comment by dternyak** [comment]
Any particular reason the gradient was changed? I don't particularly mind, but I don't want to make a lot of changes to such prominent pieces of the site without good reason and approval from other stakeholders.

**Comment by tayvano** [comment]
FYI, Jordan, myself and Avani should have been pinged on this to give feedback. I shouldnt have to accidentally stumble on this PR

**Comment by Azarielle** [comment]
@tayvano How about since I'm going through prs and stuff, if there is anything design related I'll post it in slack channel as they come it?

**Comment by james-prado** [comment]
@dternyak @tayvano Removing the gradient was a change made in the ledger monero app designs in zepplin. The designs didn't really go through much of a review before I began implementation since I was about to leave on vacation. The changes were made in [this WIP branch](https://github.com/MyCryptoHQ/MyCrypto/tree/xmr-ledger), and I cherry picked the commit with the change.

The change shouldn't be made in this pr anyway, and will be reverted.

**Comment by dternyak** [comment]
Closing for now pending further design discussion - can reopen after design approvals.

**Pull request closed without merging**
