### PR TITLE
chore/update react version

### PR DESCRIPTION
**Pull request by vilsbole**
*To help us understand & test your amazing contribution, please include the below information with your PR. 🙏 Thanks!*

### Closes
We need to update the version of react in order to use Hooks 
🎉 🎉 🎉

### Description
Update React version to v.16.8.6 in order to use Hooks!
......

### Changes
* update react and react-dom
* update packages that had errors

### Steps to Test
* run the app and navigate

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Jest is having syntax errors, you may need to install `babel-jest` or tweak Jest's config file.

**Comment by vilsbole** [comment]
Reading the logs, Jest fails to parse the files in:
- ` spec/pages/SendTransaction.spec.tsx`
- `spec/pages/ENS.spec.tsx`
I'll try to adapt the config to parse them, but I don't understand why it's happening now.
None of the configuration or test files have been modified. 🤕

**Comment by nickmccurdy** [comment]
You might need to configure it to process ES modules in node_modules

**Comment by vilsbole** [comment]
Solved it by finding the offending import statement from `react-spring`.
https://github.com/babel/babel/issues/9543

**Pull request merged**
