### PR TITLE
Remove REP under Equivalent Values

### PR DESCRIPTION
**Pull request by KanteLabs**
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/2097

### Description

No longer includes Augur(REP) equivlent values, while viewing your wallet balance currency exchange.

### Changes

* Removed refrences to REP

### Steps to Test

1. Connect & unlock wallet
2. Check all paths under /account/
3. Verify that REP is no longer included with BTC and ETH. 

### Screenshots

Before: https://user-images.githubusercontent.com/26891718/43655628-424dc2c8-9704-11e8-9916-576d85c85954.png

After: https://i.imgur.com/umkXA6k.png

### CODE REVIEW

**Comment by tayvano** [comment]
Lgtm.

Can you just remove the changes to package.json. That's the only thing that gives me pause about merging this.

**Comment by KanteLabs** [comment]
@tayvano I believe those changes are only prettier, but to be safe I just copied the package.json that was found on https://raw.githubusercontent.com/MyCryptoHQ/MyCrypto/develop/package.json and override mine. Since I couldn't revert my change of it.

**Comment by KanteLabs** [comment]
@nickmccurdy this has also been updated.

**Comment by Azarielle** [comment]
Merged into https://github.com/MyCryptoHQ/MyCrypto/pull/2447

**Pull request closed without merging**
