### PR TITLE
Update POA Node URL

### LINKED ISSUE #1984: Change RPC Endpoint for POA.network
Infura has provided their support for https://poa.network
Hence the  new URL endpoint  will be:
https://poa.infura.io
instead of 
https://core.poa.network

Similar PR has been made to MEW repo:
https://github.com/kvhnuke/etherwallet/pull/1926

I will try to figure  out how to make ~same change for MyCrypto, but let me know if there is some process that I'm not aware of.

Creating this issue in order to provide following PR

### PR DESCRIPTION
**Pull request by rstormsf**
Closes #1984 

I tried to deploy it on Github Pages, but I couldn't figure out how to append `/myownURL` to all paths, so I could use it for GH-pages

Tests:

```

Test Suites: 54 passed, 54 total
Tests:       803 passed, 803 total
Snapshots:   14 passed, 14 total
Time:        103.883s
Ran all test suites.
✨  Done in 106.25s.
```

### CODE REVIEW

**Comment by eosclassicteam** [comment]
@rstormsf Wow, how come infura support POA Network?? Amazing

**Comment by dternyak** [comment]
I'm getting a mismatch on balances when using a test address via view-only. @rstormsf Mind helping to understand what the discrepancy is caused by?

screen shot 2018-06-27 at 12 29 28 am

https://poaexplorer.com/address/0x99a39d3a0f3237bb055c826cdc94d5a7ff5d8493

**Comment by rstormsf** [comment]
@dternyak 
MEW has merged:
https://github.com/kvhnuke/etherwallet/pull/1926

**Comment by dternyak** [comment]
@rstormsf I'm still getting issues on mycryptobuilds. Any ideas on how to debug?

**Comment by rstormsf** [comment]
@dternyak I  can also see the MyCrypto received 400  errors while
https://rstormsf.github.io/etherwallet/ - works just fine

**Comment by rstormsf** [comment]
@dternyak 
Infura has confirmed the issue from their end.
Awaiting the resolution

**Comment by rstormsf** [comment]
@dternyak 
update on the issue:
Infura has found the problem that with every request, they are rejecting `id` field if it's string, allowing only integers to accept. They are working on a fix to accept both types strings and number when you send JSONRPC request.

I will let you know when they fixed it.

Thank you for waiting

**Comment by rstormsf** [comment]
@dternyak it  seems like I changed type to `infura` and now everything is working fine:

https://mycryptobuilds.com/115d2db8ba3afbff5aad5795db2b6f6839b2036c/#/account/info

**Comment by rstormsf** [comment]
@dternyak ping

**Comment by dternyak** [comment]
Tested, can confirm the fix. Looks good to merge.

**Pull request merged**
