### PR TITLE
Return missing properties from MnemonicWallet

### PR DESCRIPTION
**Pull request by kunstefix**
- add missing properties to be returned from MnemonicWallet
- read dPath from sender account instead from state

### CODE REVIEW

**Comment by LinFeiLong** [comment]
@kunstefix For me the behavior is still the same, I'm having a blank screen juste after this one
Screenshot 2019-12-19 at 13 43 48

**Comment by kunstefix** [comment]
@LinFeiLong  Thanks for noticing. I found that this bug is not present only in electron, but also on webapp. So I fixed it, but didn't test in production build (it worked in development). I will try to add another commit here to fix production as well.

**Comment by kunstefix** [comment]
@LinFeiLong  Looks like maOS production build fails because of another issue caused by Node library
image

**Comment by LinFeiLong** [comment]
if you check the ticket detail on top

Bump electron from 3.1.0 to 4.0.0      8f25c10

may have caused the issue

**Comment by LinFeiLong** [comment]
@kunstefix I read your comments ahead again.
Are you sure, the issue is only in production build ?
If so the only thing that can may cause the issue is how we build it.
what do you think ?

**Comment by LinFeiLong** [comment]
@vilsbole So I checked what you said about ripemd160. It definitely helped 
https://github.com/electron/electron/issues/16195

**Comment by LinFeiLong** [comment]
Screenshot 2020-01-08 at 12 52 28

**Comment by LinFeiLong** [comment]
Screenshot 2020-01-08 at 08 39 10

**Comment by LinFeiLong** [comment]
@kunstefix 

> add missing properties to be returned from MnemonicWallet
> read dPath from sender account instead from state

Tell me if it is still relevant to keep this

**Comment by kunstefix** [comment]
@LinFeiLong This was a fix to another bug related to Mnemonic, so it should be merged.

**Comment by kunstefix** [comment]
@vilsbole @LinFeiLong  now that node problems are fixed we should still merge this one. It fixes this undocumented bug for adding account with mnemonic: 
ezgif com-video-to-gif

**Comment by kunstefix** [comment]
> I was wondering where we set `state.selectedDPath` and the setter appears to have been removed.
> Though looking at:
> 
> ```
>  const signerWallet = await ethers.Wallet.fromMnemonic(
>       this.state.phrase,
>       this.state.selectedDPath
>     );
> ```
> 
> It is called in another place in the component.
> Should we remove the state attribute and update the code here as well?

Yes, i removed it.

**Pull request merged**
