### PR TITLE
Add Polygon memberships

### PR DESCRIPTION
**Pull request by FrederikBolding**

### CODE REVIEW

**Comment by FrederikBolding** [comment]
[ch8742]

**Review by blurpesec — COMMENTED** [review]
Not detecting my accounts that have USDC (Polygon) - despite balance showing correctly on dashboard. Poke me if you need an example account.
image

**Review by blurpesec — COMMENTED** [review]
Getting stuck on this step, won't let me proceed:
image

After clicking the "Confirm Transaction" button, no error message appears. Looking in the Network tab of chrome devtools, i see the jsonrpc request succeeded but had wrong resultant data: 
image

**Review by blurpesec — APPROVED** [review]
lgtm!

**Pull request merged**
