### PR TITLE
Add existing account views

### PR DESCRIPTION
**Pull request by SharonManrique**
###### To play around on this: 
https://mycryptobuilds.com/add-existing-account-views

### To Start - Research and things to figure out:
1) - [x] Figure out how to pass data between views. Blocked by (2).

@nickmccurdy and @blurpesec ~think it makes sense to use Formik for this, so we're going to try and do it this way~. *Sharon has a better way*. Next steps are these:
- - [x] Identify a wallet type to test implementation of this on first. Try to implement. Figure out a process. to use for other wallet types.
- - [x] Extract modal logic for select address to it's own view - Waiting on this: #2495
- - [x] Figure out handling of account logic - Completed in:  #2493 - Still needs "Back" button reverse state interaction handling
- - - [x] Wallet Type Handling.
- - - [x] Network Handling.
- - - [x] Address Selection & Derivation Path Handling.
- - [x] Duplicate to the others.
2) - [x] Determine which data needs to be created in the flow.

This is the account structure we need to fill out during the flow:
```
export interface Account {
  label: string; <- User-input
  address: string; <- User-selected after connecting wallet (may be hd, may not be)
  network: string; <- User-selected in Network dropdown after clicking on wallet type
  localSettings: string; <- Defaults to a standard value
  assets: string; <- Defaults based on network
  accountType: string; <- Wallet type (ledger vs trezor)
  value: number; <- Lookup conducted on visiting dashboard
  transactionHistory: string; <- Create new Tx History using TransactionHistoryProvider. Doesn't need to autopopulate with any data.
}
```

###### Wallet Types (verified working)

- [x] Ledger
- [x] Trezor
- [x] SafeT Mini
- [x] Web3 - @Sonicrida - #2538
- [x] Parity Signer - @blurpesec - #2548
- [x] Keystore
- [x] Mnemonic
- [x] Private Key
- [x] ViewOnly

###### Styling Changes

- [x] WalletDecrypt-wallets top-padding issue
- [x] Panel sizing/alignment in Network Selection view
- [x] Take a look at Typography font-sizing to allow things to fit in page easier

- [x] *For Each Wallet Type Please Verify*:
- - [x] No Unlock Button alignment/sizing issues
- - [x] No Wallet - Description alignment/sizing issues
- - [x] No Padding on Wallet-Image issues
- - [x] No Padding on Unlock panel issues

###### Logic Changes
- [x] Change accountData information depending on network - @blurpesec - #2528
- - [x] Asset (should be set to base asset of each network)
- - [x] Label (get feedback on this, currently set to "New Account")
- - [x] LocalSettings (figure out some default value for this and set it)
- - [x] TransactionHistory (leave as empty string until filled in by user..?)

- [x] Fix routing to dashboard at end of flow to occur *AFTER* account is added to localCache - @blurpesec - #2532
- [x] Get rid of "Confirm Address" page as it's not in designs, automatically route to dashboard. - @blurpesec - #2532

###### No-Accounts Handling Changes
- [x] Handle Dashboard no-accounts and route to new no-accounts page on component mount, instead of page refresh :-) - @SharonManrique - #2529
- [ ] Add link to "Import Wallet Settings" button - @SharonManrique 

###### ToDo Before Merge
- [ ] Have the team test functionality of wallets / look at design implementation.
- [x] Replace static copy with `translateRaw()` implementations.
- [x] Remove the "Override this" button for insecure wallet types in web.
- [x] Verify that all Wallet-Types work and propagate address to dashboard.
- [x] Clean up linting/prettier issues.
- [x] Clean up all logging statements (console.log(), debug(), etc)

### CODE REVIEW

**Comment by nickmccurdy** [comment]
We have some feedback from our designer:
- the top banner doesn’t look right? the icons / arrows are not the right colors 😞let me know if you need guidance on this
- there should be a line break after the word “mycrypto” in the 2nd line on top section: “It’s Time To Use MyCrypto For Your Crypto.” [if we can figure out a way to translate the line break positions between languages]
- image on top section seems slightly too big. can you scale down by 10-15%?
- try using hover state for panels
- “view your dashboard” txt needs to be right aligned
- testimonials section is missing yellow graphics
- Can you unbold “Have Questions? We’re Here to Help!” at bottom?
- we are missing the graphics on the “Ready to start
managing your funds safely and confidently? ” section on mobile. Can we put these on Desktop too?

**Comment by CryptoQueen628** [comment]
[ch37]

**Comment by CryptoQueen628** [comment]
[ch37]

**Comment by CryptoQueen628** [comment]
[ch37]

**Comment by nickmccurdy** [comment]
I'm not sure if this is related to the code or a random issue, but I get this integrity check failure on Chrome for mycryptobuilds (works fine locally in development and downloadable builds):
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://mycryptobuilds.com/add-existing-account-views/client.undefined.js' with computed SHA-256 integrity 'jsi+seBNfOriRx4ifF5j/xcDON7JNlsBOuqUMakyWSY='. The resource has been blocked.
```

**Pull request merged**
