### PR TITLE
Updates to master contracts list per PR#3072

### PR DESCRIPTION
**Pull request by bowensanders**
as per https://app.clubhouse.io/mycrypto/story/5410/easy-chore-use-updated-legacy-eth-contracts-list-on-beta-as-well -
Taylor's edited list was merged to legacy. 
I double checked for any differences in original versions, and they were the same.
This is a copy of the version of legacy /common/config/contracts/eth.json

Any additional contract additions will be in a later PR

see also https://github.com/MyCryptoHQ/MyCrypto/pull/3072

### CODE REVIEW

**Comment by bowensanders** [comment]
[CH5410]

**Comment by jspence425** [comment]
List looks good 👍

**Comment by jspence425** [comment]
Looks good

**Comment by blurpesec** [comment]
@bowensanders Can you update these two `70`s to be `42`'s ?https://github.com/MyCryptoHQ/MyCrypto/blob/master/common/v2/database/v1.0.0/generateDefaultValues.spec.ts#L24-L35

This will fix the tests that are currently failing in this pr.

**Comment by bowensanders** [comment]
Requested changes made, checks have passed :)

**Pull request merged**
