### PR TITLE
[IN COMMUNITY RELEASE] RIF Token for mainnet and testnet

### LINKED ISSUE #2273: RIF Token
### Description of the Feature

RIF Token available in MyCrypto

### PR DESCRIPTION
**Pull request by alepc253**
Closes #2273

### Description

Contract and Token for `RIF` in mainnet and testnet `RSK` network

### Changes

* Config files

### Steps to Test

1. Choose `RSK` network (either mainnet or testnet)
2. Go to "Contracts", then "Interact"
3. Check `RIF` contract is available for mainnet (or `tRIF` for testnet)

### CODE REVIEW

**Comment by alepc253** [comment]
@ConnorBryan is there any problem with CI build? I've seen other PRs with the same failure

**Comment by ConnorBryan** [comment]
@alepc253 Let me manually retrigger it.

**Comment by alepc253** [comment]
Already fixed... I triggered again with a minimum change

**Comment by alepc253** [comment]
@ConnorBryan had to change `tRIF` address, sorry and thanks!

**Pull request merged**
