### PR TITLE
Ak 2124 disabled verify for invalid address

### LINKED ISSUE #2124: Verifying an invalid signed message should not be allowed
When verifying a message, you should not be able to select the button "Verify Message" until you have inputted a valid message to verify. 

image

### PR DESCRIPTION
**Pull request by KanteLabs**
Closes #2124

### Description

When verifying a message, you should not be able to select the button "Verify Message" until you have inputted a valid message to verify.

### Changes

* On paste checks if the signautre is valid to enable or disable the verify message button
* On change (user typing) also checks to see if the signature is valid
* You Made

### Steps to Test

1. Paste or type in an invalid signature and the "verify message" button should be disabled still.
2. Paste or type in a valid signature and the "verify message" button should be enabled. 
3. If you delete or change a valid signature the "verify message" button should go back to disabled. 

### Screenshots
Before: https://user-images.githubusercontent.com/25834495/44283848-a4634f80-a22d-11e8-933e-ad00384effbc.png

After:  (Invalid signature) https://i.imgur.com/JnehNsm.png

### CODE REVIEW

**Comment by KanteLabs** [comment]
@tayvano  I went ahead and override my package.json with the one from develop. For some reason, the one I have keeps getting committed.

**Comment by KanteLabs** [comment]
@ConnorBryan @tayvano @Azarielle Just checking the status of this pull request, to see if it will be merge? Since it has been left open for a while now.

**Comment by nickmccurdy** [comment]
There are merge conflicts in package.json

**Comment by KanteLabs** [comment]
@nickmccurdy okay i updated the pull. I can also update this pull if you can review it https://github.com/MyCryptoHQ/MyCrypto/pull/2201

**Pull request merged**
