### PR TITLE
Add OpenWeb Network Contract and ABI

### PR DESCRIPTION
**Pull request by openweb-network-user**
Adding openweb contract ABI to default list

### CODE REVIEW

**Comment by blurpesec** [comment]
@openweb-network-user Heya, can you add your token [here](https://github.com/ethereum-lists/tokens/tree/master/tokens/eth) please - we pull our token data from that repo.

**Comment by openweb-network-user** [comment]
@blurpesec sure, what about contract address and ABI ?

**Comment by openweb-network-user** [comment]
https://github.com/ethereum-lists/tokens/pull/211

**Comment by openweb-network-user** [comment]
Great, Thanks for the help :)

**Pull request merged**
