### PR TITLE
(LEGACY) Added Telegram link in footer

### PR DESCRIPTION
**Pull request by 409H**
[CH6189]

🎉 🎉 🎉

## Description

* Added option to add an svg icon to the SocialMediaLink part as the fontpack we use does not support everything

Screenshot 2020-05-27 at 22 43 54

## Changes

* Changes to the `Link` interface to have a new property `icon` to specify an svg

## Quality Assurance

- [ ] The branch name is in lowercase-kebab-case with no prefix (unless it was created from Clubhouse)
- [ ] The base branch is develop or gau (no nested branches)
- [ ] This is related to a maximum of one Clubhouse story or GitHub issue
- [ ] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] If code is copied from existing directories, there is an explanation of why this is necesary in the description/changes, and all copying is done in separate commits to make them easy to filter out
- [ ] If your code adds new text to the UI, the added text is [translatable](https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributing---Translatable-strings)

### CODE REVIEW

**Comment by wtzb** [comment]
Would love to get this in the new release I'm QA'ing. Could you tell me where the `icon: null`'s are for?

**Comment by 409H** [comment]
I had to modify the interface of `Link` to include a new property of `icon` since the fontpack does not include the Telegram icon, so we have to do the Telegram icon differently with an SVG. The `icon` property is to hold the SVG.

**Comment by wtzb** [comment]
It shows up a bit funny for me. Using Linux, both latest Chromium and Firefox (incognito and normal).

image

Setting .LogoBox to be a min-width of 290px seems to fix it for me.

image

**Comment by wtzb** [comment]
Accidentally closed - my bad :)

**Pull request merged**
