### PR TITLE
Added label sort to address book table

### PR DESCRIPTION
**Pull request by blurpesec**
### Description
Add label sort to the address book table in the settings.

### CODE REVIEW

**Comment by blurpesec** [comment]
[ch6778]

**Comment by FrederikBolding** [comment]
image

This doesn't seem to be sorted by label by default correctly?

**Review by FrederikBolding — CHANGES_REQUESTED** [review]
See above

**Comment by blurpesec** [comment]
> See above

This label sort is for the Address Book table, not the Account table :)

**Comment by FrederikBolding** [comment]
My bad 😆

**Review by FrederikBolding — APPROVED** [review]

**Pull request merged**
