### PR TITLE
Add support for Permission (ASK) blockchain

### PR DESCRIPTION
**Pull request by seanmcgary**
## Description

Permission is a fork of Ethereum to enable a permission-based, decentralized digital advertising marketplace.

* Home page: https://permission.io
* Node: https://blockchain-api-mainnet.permission.io/rpc
* Explorer: https://explorer.permission.io
* BIP44 PR:  https://github.com/satoshilabs/slips/pull/641
* Trezor support PR: https://github.com/trezor/trezor-firmware/pull/200

## Changes
This PR adds support for the Permission mainnet blockchain.

### CODE REVIEW

**Comment by SharonManrique** [comment]
@seanmcgary Thank you for the contribution! Your pr will be included in our next release -> 1.6.8 :)

**Comment by seanmcgary** [comment]
@SharonManrique Excellent, thanks so much!

**Comment by seanmcgary** [comment]
@SharonManrique is there a reason that this was closed rather than merged? Do I maybe need to update my brach to pull in some upstream changes? Or do you guys cherry-pick in changes manually (rather than merging)? Just want to make sure Im not missing something!

**Comment by SharonManrique** [comment]
@seanmcgary I merged it into my local, but didn't push. I'm so sorry about that. I'm updating release right now. Thank you for pointing this out!

**Comment by seanmcgary** [comment]
No worries at all! Had a feeling something like that happened (totally done that before myself) and just wanted to make sure 😄

**Comment by SharonManrique** [comment]
@seanmcgary It has been officially merged. :+1:

**Pull request merged**
