### PR TITLE
Disable buttons on confirmation modal when transaction is broadcasting

### LINKED ISSUE #1911: Remove buttons once a user has pressed the "Send" button on the confirmation dialog
The buttons on the confirmation dialog should disappear or become invalid once the user has pressed the send button and the display changes to a loading icon. 

2018-06-06 at 4 06 05 pm

---

The above was composed from the video demo provided by the user here: https://app.hyfy.io/v/abDI1dq7frn/#!/player

Please ping Taylor/Jordan to update user via twitter when complete: https://twitter.com/scottmberry/status/1004481904148561920

### PR DESCRIPTION
**Pull request by ConnorBryan**
Closes #1911

### Description

Fixes an issue where the confirmation modal would show clickable actions while transaction was being processed.

### Changes

* Modals now properly pass down the `disableButtons` property to their body.

### Steps to Test

1. Perform a transaction.
2. When the confirmation modal opens, click "Send".
3. The buttons should be visible and disabled.

### CODE REVIEW

**Comment by ConnorBryan** [comment]
Opted to hide buttons while broadcasting:

screen shot 2018-06-26 at 2 21 40 pm

**Comment by ConnorBryan** [comment]
@dternyak I just caught the animation at a weird time, lol

**Comment by wbobeirne** [comment]
The problem is that the modal has this fade element that covers some of the content. The spinner seems to get touched by that. You could either hide the fade, or move it to the bottom while the buttons are missing.

**Comment by ConnorBryan** [comment]
@dternyak @wbobeirne 

Fixed:

screen shot 2018-06-29 at 11 54 48 am

**Pull request merged**
